### ISSUE TITLE
[ Errno 2 ]

### ISSUE THREAD

**Issue by illiaGoncharov** [xiumingzhang/mosculp-demo-ui#1]
Trying to return `kivy main.py` in Teminal. 
`/Applications/Kivy2.app/Contents/Resources/python: can't open file 'main.py': [Errno 2] No such file or directory` returned.
"python" as I can see is not a directory. 
`file *` returns ```python:             Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [i386:Mach-O executable i386]
python (for architecture x86_64):	Mach-O 64-bit executable x86_64
python (for architecture i386):	Mach-O executable i386```. 
I'm not that cool yet to solve this issue by myself so I would appreciate any help!

**Comment by xiumingzhang** [comment]
Did you run this command in the directory with `main.py` inside? What is the output of `ls` at where you ran `kivy main.py`? Feel free to reopen this if it is not resolved.
